mastodon/mastodon-android

mastodon/src/main/java/org/joinmastodon/android/api/CacheController.java

Thanks for developing this elegant app!
I encountered a crash caused by new sign up notifications so I made a quick fix for that.
If you think there's better way to fix this problem, feel free to close this PR.
```
E/AndroidRuntime: FATAL EXCEPTION: databaseThread
Process: org.joinmastodon.android, PID: 1642
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.joinmastodon.android.model.Notification$Type.ordinal()' on a null object reference
at org.joinmastodon.android.api.CacheController.lambda$putNotifications$9(CacheController.java:200)
at org.joinmastodon.android.api.CacheController$$ExternalSyntheticLambda5.run(Unknown Source:6)
at org.joinmastodon.android.api.CacheController.lambda$runOnDbThread$14(CacheController.java:268)
at …
```

Fix notification crashes caused by unknown notification type

---

mastodon/src/main/java/org/joinmastodon/android/ui/views/ComposeEditText.java

Fixes #90 
The call to `super.onCreateInputConnection` was overwriting the mimes in the `outAttrs`, so we can call that first and then modify the mimes.
This fixes the ability to insert GIFs with the default GBoard GIF menu for me.

Fix receiving images from keyboards

---

mastodon/src/main/java/org/joinmastodon/android/api/requests/accounts/GetPreferences.java
mastodon/src/main/java/org/joinmastodon/android/fragments/ComposeFragment.java
mastodon/src/main/java/org/joinmastodon/android/model/ExpandMedia.java
mastodon/src/main/java/org/joinmastodon/android/model/Preferences.java
mastodon/src/main/java/org/joinmastodon/android/model/StatusPrivacy.java

Fixes #266 
This queries the user's post visibility preference when opening the composer, and sets it on the composer.
In the case of composing a reply, the user's preference is only respected if it is "more private" than the privacy of the post being replied to, as this appears to be the behaviour in the web interface (and is what I'd expect)

Load post privacy preference

---

mastodon/src/main/java/org/joinmastodon/android/ui/text/HtmlParser.java

Fixes #274
Add a merge function to `Collectors.toMap` to discard any duplicate custom emojis that may be returned if a user uses the same custom emoji in both their name and profile.

Fix crash on duplicate custom emojis

---

mastodon/src/main/java/org/joinmastodon/android/fragments/NotificationsListFragment.java

Fixes #227, caused by an edge case where a notification type was "status", but "status" was null. This caused the `buildDisplayItems` method (in `NotificationsListFragment`) to falsely assume the `titleItem` to not be null, resulting in a null pointer exception and the app crashing.

Check whether title status item is null to fix null pointer exception

---

mastodon/build.gradle
mastodon/src/main/AndroidManifest.xml
mastodon/src/main/res/xml/locales_config.xml

Add Android 13 per-app language preferences to allow multilingual users set their system language to one language but select another languages for the app.

Add Android 13 per-app language preferences

---

mastodon/src/main/res/layout-w600dp/button_bar_activation.xml
mastodon/src/main/res/layout/button_bar_activation.xml
mastodon/src/main/res/layout/fragment_onboarding_activation.xml

Fix the button bar layout in the onboarding activation screen for screens with smaller width by creating separate layouts for default and `w600dp`.
Before
After

Fix button bar layout in onboarding activation for smaller widths

---

mastodon/src/main/res/layout/item_instance_category.xml

Fix CJK text cut off for category names on Onboarding screen by reducing padding and increasing TextView height by 2dp.
Please let me know if that would be an OK solution for you.
Before:
After:

Fix CJK text cut off for category names on Onboarding screen

---

mastodon/src/main/res/layout/display_item_header.xml

The screen reader (tested with TalkBack) used to read aloud the username, “middle dot”, [time left]

Omit “middle dot” for screen reader

---

mastodon/src/main/java/org/joinmastodon/android/api/gson/IsoInstantTypeAdapter.java
mastodon/src/main/java/org/joinmastodon/android/fragments/ProfileAboutFragment.java

For at least my server, I'm getting a response back from the `/accounts/:id` endpoint that has value that the client doesn't currently parse:
```
$ curl -s https://hachyderm.io/api/v1/accounts/109343416337534779 | jq '.fields[1].verified_at'
"2022-11-14T19:09:55.195+00:00"
```
This change adds support for formatting via `DateTimeFormatter.ISO_OFFSET_DATE_TIME` as well as the current strategy.
With this in place, the `verifiedAt` property of the field item is populated correctly.
I've naively changed the background color of the view to mimic the color in the ios app which was set here: https://github.com/mastodon/mastodon-ios/pull/564/files#diff-9f9b076de09fb062f0ac69c0392cbce9eece78a09cc0fb68fefd519dfce6760eR4-R10
fixes #125
That said, I didn't go any further to add a checkmark or add …

Add Support for showing "Verified" fields on the Profile | About View

---

mastodon/src/main/java/org/joinmastodon/android/ui/ComposeAutocompleteViewController.java

When searching for emojis by typing `:emoji_name`,
* Display `.startsWith` matches first
* Below, also display emojis that don't start with the searched string, using `.contains`
* Search case-insensitive instead of case-sensitive

Improve inline emoji search

---

mastodon/src/main/java/org/joinmastodon/android/api/PushSubscriptionManager.java

The previous fix https://github.com/mastodon/mastodon-android/pull/486 would break any connections to any instances using WEB_SAFE MIME64 encoding on the serverKey, which actually appears to be the usual case.
This update reverts to the previous logic, but also converts standard MIME64 characters ('/' and '+') to their WEB_SAFE equivalents.
This ensures the standard case of WEB_SAFE BASE64 serverKeys and the anomalous case of DEFAULT BASE64 keys both work.

Second fix for MIME64 inconsistency in serverKey.

---

mastodon/src/main/java/org/joinmastodon/android/fragments/ComposeFragment.java

There's a bug where, when restoring the saved ComposeFragment instance twice, the spoiler would disappear.
Turns out this is the case because the "hasSpoiler" value isn't properly restored when loading the spoiler back into place for the first time – so the second time, "hasSpoiler" will be `false` even though there would be a spoiler value to restore.

Fix wrong "hasSpoiler" value on restore

---

mastodon/src/main/java/org/joinmastodon/android/fragments/NotificationsFragment.java

In case this wasn't deliberately left out: This enabled the same behavior as in Profile and Discover – scrolling to the top by clicking the toolbar or the selected tab.

Enable scrolling to top by tapping Notifications toolbar

---

mastodon/src/main/res/layout/fragment_compose.xml

The compose toolbar's ImageButtons are only 24dp in width and height, but their ripple background suggests otherwise - which is not great for accessibility as the buttons are really easy to miss, leaving the user to wonder why.
Using "actionBarItemBackground" instead of the "selectableItemBackgroundBorderless" makes the ripple more adjacent to the actual hitbox, which I have therefore increased to 36dp:

Bigger hitbox for items in compose toolbar

---

mastodon/src/main/java/org/joinmastodon/android/model/Instance.java
mastodon/src/main/java/org/joinmastodon/android/ui/tabs/TabLayout.java

Fixes two typos in comments found via `codespell  -S ./mastodon/src/main/res,./fastlane,./mastodon/src/main/java/com`.

fix: typos

---

mastodon/src/main/java/org/joinmastodon/android/ui/text/ClickableLinksDelegate.java

I have added a small change to the ClickableLink views, allowing a new action to copy the link text rather than opening it.
I also did some minor refactoring in the affected file, because I didn't want to copy existing (and already reused) code a third time.
Resolves https://github.com/mastodon/mastodon-android/issues/537

clickable links: add "hold to copy" action

---

mastodon/src/main/java/org/joinmastodon/android/fragments/discover/SearchFragment.java

Fixes an error message, which would appear, if the search query was blank.

fix(search): check for empty queries

---

mastodon/src/main/java/org/joinmastodon/android/fragments/discover/TrendingHashtagsFragment.java
mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/HashtagStatusDisplayItem.java

closes mastodon#468
closes sk22#523
Adds null and isEmpty checks for `history` in `Trending-`/`HashtagStatusDisplayItem`, so Mastodon will display only the hashtag name without the trending history information instead of crashing.

Fix crash when searching for Hashtags on Akkoma servers

---

mastodon/src/main/java/org/joinmastodon/android/fragments/StatusListFragment.java

When voting on polls that got boosted into your timeline and then tapping it to open the thread, the poll appears as if you hadn't already voted, and allows to (try to - it'll fail with a validation error) vote again. This fixes the issue by passing the `contentStatus` down to `updatePoll` (which just replaces the `poll` property of that status with the updated one).

Fix poll not updating content status when boosted

---

mastodon/src/main/java/org/joinmastodon/android/model/Instance.java

I noticed this while testing the Mastodon app with Calckey / Firefish. The Mastodon app does work on iOS but on Android this causes a crash before signup/sign-in.
I propose to add an additional array length check to ensure the languages array is not empty in order to prevent this crash.

Do not assume languages array will contain entries

---

mastodon/src/main/java/org/joinmastodon/android/fragments/ComposeFragment.java

This fixes an issue where if the amount of images that are allowed to be selected are less than 2 and the EXTRA_PICK_IMAGES_MAX property is set as 1 the image picker wouldn't popup.

fix(compose): fix photoPicker not popping up when there is less than 2 spaces available for media

---

mastodon/src/main/java/org/joinmastodon/android/fragments/ComposeFragment.java
mastodon/src/main/java/org/joinmastodon/android/ui/viewcontrollers/ComposeMediaViewController.java

See also: https://github.com/tuskyapp/Tusky/pull/4068
----
Steps to reproduce:
1. install Gboard
(https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin)
2. open a direct link to any image in Firefox
3. long-press the image to get a "Copy Image" dialogue (and copy the
image)
4. compose a new post in Mastodon for Android
5. Gboard will suggest to paste the image from clipboard
6. paste image, see that when opening alt text editor, it is filled out
with this garbage string
Why is this bad? It's not when I just fix the alt text. But it breaks
every mechanism that is supposed to remind me of adding alt text.
It's hard to argue that this is within scope of this app but I
also don't see it getting fixed in Gboard, so here we go.

Remove garbage alt text from images attached via Gboard

---

mastodon/src/main/java/org/joinmastodon/android/api/requests/statuses/GetStatusEditHistory.java
mastodon/src/main/java/org/joinmastodon/android/ui/utils/InsetStatusItemDecoration.java

Fixes a problem where the application would crash when opening and closing the content warning of a post in the edit history screen, caused by trying to access index `-2` of the array.
Also fixes an issue where the edit history could not be displayed if it contained a poll, due to the API response not providing required fields. I can move this commit to a separate pull request if you prefer. There is also an issue where the poll is still clickable, but I'm not sure what the best way to fix this is.

fix: edit history crash

---

mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/HeaderStatusDisplayItem.java
mastodon/src/main/java/org/joinmastodon/android/ui/utils/UiUtils.java

Fixes an issue, where due to the group divider being enabled, the menu item is not visible.

fix: disable group divider on EMUI

---

mastodon/src/main/java/org/joinmastodon/android/fragments/BaseStatusListFragment.java
mastodon/src/main/java/org/joinmastodon/android/model/Translation.java
mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/MediaGridStatusDisplayItem.java
mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/PollOptionStatusDisplayItem.java
mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/SpoilerStatusDisplayItem.java
mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/StatusDisplayItem.java

Adds the ability to translate not only status text, but also media attachment descriptions (alt text) and poll options, a new feature introduced in [4.2.0](https://github.com/mastodon/mastodon/releases/tag/v4.2.0).
| Untranslated                                                                                                       	| Translated                                                                                                      	|
|--------------------------------------------------------------------------------------------------------------	|------------------------------------------------------------------------------------------------------------	|
| ![Untranslated poll](https://github.com/mastodon/mastodon-android/assets/63370021/8b6f5af4-daeb-4e75-83e7-66907c6133ec) 	| …

Allow translation of attachments, spoilers and polls

---

mastodon/src/main/java/org/joinmastodon/android/api/session/AccountSessionManager.java

Fixes app failing to delete the `$id.xml` shared pref on Android M, because `getDir("shared_prefs"..)` for some reason returns `/data/.../app_shared_prefs/` dir, which is empty or non-existent.
To reproduce:
1. log into any account
2. log out
3. observe `shared_prefs/id.xml` pref still there

Delete `id.xml` shared pref from the correct dir

---

mastodon/src/main/java/org/joinmastodon/android/ui/viewcontrollers/ComposeLanguageAlertViewController.java

Closes https://github.com/mastodon/mastodon-android/issues/766
the `detected` added to `specialLocales` may have nullable `locale`(which should be initialized in `detectLanguage()` later)
https://github.com/mastodon/mastodon-android/blob/48f9aabaf7f0b329d5e04583ef2b817f0301dc6c/mastodon/src/main/java/org/joinmastodon/android/ui/viewcontrollers/ComposeLanguageAlertViewController.java#L83-L89
and this will cause `NullPointerException` in line 100
https://github.com/mastodon/mastodon-android/blob/48f9aabaf7f0b329d5e04583ef2b817f0301dc6c/mastodon/src/main/java/org/joinmastodon/android/ui/viewcontrollers/ComposeLanguageAlertViewController.java#L99-L107
add nullable check

fix: NullPointerException crash while change post language twice

---

mastodon/src/main/java/org/joinmastodon/android/fragments/ProfileFragment.java

Fixes a similar issue as https://github.com/mastodon/mastodon-android/pull/732, introduced in https://github.com/mastodon/mastodon-android/commit/eacfd2fa4f7e3df7ae008675a2e946d791f33e95.

fix: disable group divider in ProfileFragment on EMUI

---

mastodon/src/main/java/org/joinmastodon/android/fragments/ProfileFeaturedFragment.java

Fixes a NullPointerExpecption caused by not passing the account from the `ProfileFeaturedFragment` to the `FeaturedHashtagsListFragment`.
Closes https://github.com/mastodon/mastodon-android/issues/803.

fix: include account when opening FeaturedHashtags

---

mastodon/src/main/java/org/joinmastodon/android/api/MastodonErrorResponse.java
mastodon/src/main/res/values/strings.xml

Instead of displaying the Java exception, this change displays a more user-friendly message for some common network-related issues.
Fixes mastodon/mastodon-android#667
Please let me know if this is a good way to implement this or what would be the best way to do it, if not.

Display more user-friendly error messages

---

mastodon/src/main/java/org/joinmastodon/android/fragments/ProfileFragment.java
mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/HeaderStatusDisplayItem.java
mastodon/src/main/java/org/joinmastodon/android/ui/utils/UiUtils.java

When enabled on [MagicOS](https://www.honor.com/global/magic-os/), GroupDividers are not displayed and causes other menu items to be invisible. Similar bug to
https://github.com/mastodon/mastodon-android/pull/732.

fix: disable GroupDivider on Honor's MagicOS

---

mastodon/src/main/AndroidManifest.xml
mastodon/src/main/res/xml/network_security_config.xml

On older Android devices the root certificates don't get updated anymore. Because the commonly used Let's encrypt root certificate expired some time ago, older Android devices are not able to connect to the mastodon servers. But the user can add root certificates manually to the user certificate store in the Android settings.
**This pull request adds the user certificate store to the list of trust anchors in the mastodon app.**
With this small code change the users of older android devices can add the root certificate to the user certificate store and connect to the mastodon servers.
I tested it on an Asus P00A with Android 7 and would appreciate it if you decide to merge this pull request.
Kind Regards.

Added network security config

---

mastodon/src/main/java/org/joinmastodon/android/api/JsonObjectRequestBody.java

Per https://datatracker.ietf.org/doc/html/rfc8259, application/json does not have a charset parameter

fix: Remove charset from application/json content type

---

mastodon/src/main/java/org/joinmastodon/android/api/session/AccountSessionManager.java

I messed up in #921 and created a rare bug as I forgot strings in sql are indexed at 1 
sqlites implementation just seems to count the characters for substr(0, x) beginning at 0, but the count is wrong so that it cuts off the last character for exactly 500KB long emoji strings (and then exactly 1.5MB)
This should be correct now :sweat_smile:

fix sql strings are indexed at 1

---

mastodon/src/main/java/org/joinmastodon/android/api/requests/accounts/AcceptFollowRequest.java
mastodon/src/main/java/org/joinmastodon/android/api/requests/accounts/RejectFollowRequest.java
mastodon/src/main/java/org/joinmastodon/android/ui/displayitems/NotificationHeaderStatusDisplayItem.java
mastodon/src/main/res/color/button_text_m3_filled_secondary.xml
mastodon/src/main/res/drawable/bg_button_m3_filled_secondary.xml
mastodon/src/main/res/layout/display_item_notification_header.xml
mastodon/src/main/res/values/strings.xml
mastodon/src/main/res/values/styles.xml

Closes #809, closes #763, closes #265, closes #105
When I was using Mastodon Android, ability to accept/decline follow requests was only one blocking feature when I had to open web client to do so.
I've added accept/reject buttons to follow request notification to reflect the same UI existing in Mastodon iOS nowadays:
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
<p>UI, implemented in this PR</p>
</td>
<td>
<p>Mastodon iOS UI</p>
</td>
</tr>
</table>

Follow requests acceptance/rejection
